"""rotacao por camera

Revision ID: cb34b695d668
Revises: c3d4e5f6a7b8
Create Date: 2026-09-11 09:20:54.039160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb34b695d668'
down_revision = 'c3d4e5f6a7b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default='0' e' obrigatorio: ja existem cameras cadastradas
    # (NOT NULL sem default falha num ADD COLUMN com linhas existentes).
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rotation', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.drop_column('rotation')

    # ### end Alembic commands ###
