"""zona de risco por camera

Revision ID: cd57c8841519
Revises: cb34b695d668
Create Date: 2026-09-19 23:58:55.546103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd57c8841519'
down_revision = 'cb34b695d668'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('risk_polygon', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.drop_column('risk_polygon')

    # ### end Alembic commands ###
