"""esquema inicial: alerts, event_logs, cameras

Baseline do que db.create_all() já produzia antes da adoção do Alembic.
Quem JÁ tem um banco criado por create_all() deve rodar
`flask db stamp f6cd160ae4e0` uma única vez e só então `flask db upgrade` —
assim a revisão seguinte (camera_id) roda sem tentar recriar tabelas.

Revision ID: f6cd160ae4e0
Revises: 
Create Date: 2026-08-24 09:35:30.909265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6cd160ae4e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule', sa.String(length=80), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('feature', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('frame_ref', sa.String(length=240), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('occurrences', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_feature'), ['feature'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_first_seen_at'), ['first_seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_last_seen_at'), ['last_seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_resolved_at'), ['resolved_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_rule'), ['rule'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_status'), ['status'], unique=False)

    op.create_table('cameras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=160), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('fps', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('features_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cameras_created_at'), ['created_at'], unique=False)

    op.create_table('event_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=120), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_logs_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_logs_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_logs_subject'), ['subject'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_logs_subject'))
        batch_op.drop_index(batch_op.f('ix_event_logs_severity'))
        batch_op.drop_index(batch_op.f('ix_event_logs_event_type'))
        batch_op.drop_index(batch_op.f('ix_event_logs_created_at'))

    op.drop_table('event_logs')
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cameras_created_at'))

    op.drop_table('cameras')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_status'))
        batch_op.drop_index(batch_op.f('ix_alerts_severity'))
        batch_op.drop_index(batch_op.f('ix_alerts_rule'))
        batch_op.drop_index(batch_op.f('ix_alerts_resolved_at'))
        batch_op.drop_index(batch_op.f('ix_alerts_last_seen_at'))
        batch_op.drop_index(batch_op.f('ix_alerts_first_seen_at'))
        batch_op.drop_index(batch_op.f('ix_alerts_feature'))
        batch_op.drop_index(batch_op.f('ix_alerts_created_at'))

    op.drop_table('alerts')
    # ### end Alembic commands ###
